version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command:
      - bash
      - -c
      - |
        python3 manage.py migrate
        python3 manage.py createadmin
        python3 manage.py runserver 0.0.0.0:5000

    volumes:
       - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
volumes:
  postgres_data: